spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: scribly-db
      auto-index-creation: true

jwt:
  secret: ${SECRET_KEY}

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

app:
  client:
    url: ${CLIENT}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.data.mongodb: DEBUG 